### PR TITLE
Add more primitives to the demo app

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
@aherrmann I've updated `samoht/mirage-lambda` on docker hub  with that branch. You can now try to connect to the unikernel and send it some protobuf messages. You won't see responses yet but you could see in the logs if the message has been processed properly, which can already be useful for testing.

Responses are being implemented soon :-)

**Comment by aherrmann** [comment]
@samoht Thanks, I've done some early tests on the provided container. It's already looking good. Here's a list of issues I encountered.

- `Retrieve an error: (Invalid_argument "Abstract type Mirage_block.info not found")` on the following message:
    ```
     Message:
       Header: Header {headerProtoSize = 242, headerBlockSize = 0, headerBlockNum = 0}
       Header (hex): f20000000000000000000000000000000000000000000000
       Request:
         expr {
           bnd {
             expr {
               prm {
                 value {
                   name: "Block.get_info"
                   return {
                     apply {
                       a { abstract { witness: "Mirage_block.info" } } b { lwt { } }
                     }
                   }
                 }
               }
             }
             func {
               lam {
                 typ { abstract { witness: "Mirage_block.info" } }
                 var: "info"
                 expr {
                   ret {
                     expr {
                       bin {
                         op: PAIR
                         a {
                           app {
                             a {
                               prm {
                                 value {
                                   name: "sector_size"
                                   arguments { abstract { witness: "Mirage_block.info" } }
                                   return { int { } }
                                 }
                               }
                             }
                             b { var { var: 0 } }
                           }
                         }
                         b {
                           app {
                             a {
                               prm {
                                 value {
                                   name: "size_sectors"
                                   arguments { abstract { witness: "Mirage_block.info" } }
                                   return { int64 { } }
                                 }
                               }
                             }
                             b { var { var: 0 } }
                           }
                         }
                       }
                     }
                   }
                 }
               }
             }
           }
         }
         typ {
           apply {
             a { pair { a { int { } } b { int64 { } } } } b { lwt { } }
           }
         }
     
       Request (hex): 0adb018201d7010a3412320a300a0e426c6f636b2e6765745f696e666f1a1e5a1c0a168201130a114d69726167655f626c6f636b2e696e666f12023a00129e013a9b010a168201130a114d69726167655f626c6f636b2e696e666f1204696e666f1a7b7a790a775275080512374a350a2d122b0a290a0b736563746f725f73697a6512168201130a114d69726167655f626c6f636b2e696e666f1a0212001204320208001a384a360a2e122c0a2a0a0c73697a655f736563746f727312168201130a114d69726167655f626c6f636b2e696e666f1a02220012043202080012125a100a0a6a080a0212001202220012023a00
       Message (hex): f200000000000000000000000000000000000000000000000adb018201d7010a3412320a300a0e426c6f636b2e6765745f696e666f1a1e5a1c0a168201130a114d69726167655f626c6f636b2e696e666f12023a00129e013a9b010a168201130a114d69726167655f626c6f636b2e696e666f1204696e666f1a7b7a790a775275080512374a350a2d122b0a290a0b736563746f725f73697a6512168201130a114d69726167655f626c6f636b2e696e666f1a0212001204320208001a384a360a2e122c0a2a0a0c73697a655f736563746f727312168201130a114d69726167655f626c6f636b2e696e666f1a02220012043202080012125a100a0a6a080a0212001202220012023a00
    ```

- Infinite loop printing `INF [application] Loop back on the un-serialization.` on the following message:
    ```
    Message:
      Header: Header {headerProtoSize = 14, headerBlockSize = 1, headerBlockNum = 1}
      Header (hex): 0e0000000000000001000000000000000100000000000000
      Request:
        expr { val { value { int32 { value: 1 } } } } typ { int32 { } }
    
      Request (hex): 0a080a060a041a02080112021a00
      Message (hex): 0e00000000000000010000000000000001000000000000000a080a060a041a02080112021a0000
    ```

- The `Request` type currently has no field to specify the number of expected output blocks.

**Comment by dinosaure** [comment]
It seems than the second issue is about:
* An error of the OCaml's `protobuf` decoder (which raises an error)
* trailing bytes (about Block) which are not consumed & considered as a header request.

**Comment by dinosaure** [comment]
@aherrmann I just fixed your first and second issue, if you can test it again 👍 !

**Comment by aherrmann** [comment]
@dinosaure Thanks!

The first issue seems resolved in that the error message `(Invalid_argument "Abstract type Mirage_block.info not found")` does not occur anymore. The output is now
```
2018-07-06 16:27:13 +00:00: INF [application] new tcp connection from IP 172.17.0.1 on port 50502
2018-07-06 16:27:13 +00:00: INF [application] We receive something.
2018-07-06 16:27:13 +00:00: INF [application] Loop back on the un-serialization.
```
It does not seem to evaluate the expression, at least it doesn't print any result.

The second issue I can still reproduce.
The setup was the following (in the `mirage-lambda` directory)
```
$ g rev-parse HEAD
2d6a94c9756540cc6b86cc0e995dc79967c73c6e
$ docker build -t mirage-lambda .
$ make block
$ docker run -it -v `pwd`/disk.img:/disk.img -p 1234:1234 mirage-lambda
```

Then sending the same message as before:
```
Message:
  Header: Header {headerProtoSize = 14, headerBlockSize = 1, headerBlockNum = 1}
  Header (hex): 0e0000000000000001000000000000000100000000000000
  Request:
    expr { val { value { int { value: 1 } } } } typ { int { } }

  Request (hex): 0a080a060a041202080112021200
  Message (hex): 0e00000000000000010000000000000001000000000000000a080a060a04120208011202120000
```
Causes a loop in the Mirage server printing many lines as
```
...
2018-07-06 16:21:07 +00:00: INF [application] Loop back on the un-serialization.
2018-07-06 16:21:07 +00:00: INF [application] Loop back on the un-serialization.
2018-07-06 16:21:07 +00:00: INF [application] Loop back on the un-serialization.
...
```
And it does not seem to react to further requests anymore.

**Comment by samoht** [comment]
@dinosaure missing deps in opam file:

```
#=== ERROR while installing lambda-protobuf.~unknown ==========================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p lambda-protobuf -j 4
# path                 /home/opam/.opam/4.05.0/build/lambda-protobuf.~unknown
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/lambda-protobuf.~unknown/lambda-protobuf-10312-ffb3fd.env
# stdout-file          /home/opam/.opam/4.05.0/build/lambda-protobuf.~unknown/lambda-protobuf-10312-ffb3fd.out
# stderr-file          /home/opam/.opam/4.05.0/build/lambda-protobuf.~unknown/lambda-protobuf-10312-ffb3fd.err
### stderr ###
# File "bin/jbuild", line 5, characters 23-30:
# Error: Library "rresult" not found.
```

**Pull request merged**
