### PR TITLE
Add missing primitives

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by aherrmann** [comment]
When I try `docker build` I get the following error
```
ocaml-protoc proto/lambda_pb.{ml,mli},proto/lambda_types.{ml,mli}
Generating ./lambda_types.mli
Generating ./lambda_types.ml
Generating ./lambda_pb.mli
Generating ./lambda_pb.ml
      menhir src/parser.{ml,mli}
Note: the nonterminal symbol list (from parser.mly) is renamed parser_list.
      ocamlc mirage/.main.eobjs/unikernel.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -cclib -static -g -bin-annot -I mirage/.main.eobjs -I /home/opam/.opam/4.06/lib/afl-persistent -I /home/opam/.opam/4.06/lib/astring -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/cmdliner -I /home/opam/.opam/4.06/lib/crowbar -I /home/opam/.opam/4.06/lib/cstruct -I /home/opam/.opam/4.06/lib/cstruct-lwt -I /home/opam/.opam/4.06/lib/duration -I /home/opam/.opam/4.06/lib/fmt -I /home/opam/.opam/4.06/lib/functoria-runtime -I /home/opam/.opam/4.06/lib/higher -I /home/opam/.opam/4.06/lib/io-page -I /home/opam/.opam/4.06/lib/io-page-unix -I /home/opam/.opam/4.06/lib/ipaddr -I /home/opam/.opam/4.06/lib/ipaddr/unix -I /home/opam/.opam/4.06/lib/logs -I /home/opam/.opam/4.06/lib/lwt -I /home/opam/.opam/4.06/lib/lwt/unix -I /home/opam/.opam/4.06/lib/mirage-block -I /home/opam/.opam/4.06/lib/mirage-block-lwt -I /home/opam/.opam/4.06/lib/mirage-block-unix -I /home/opam/.opam/4.06/lib/mirage-clock -I /home/opam/.opam/4.06/lib/mirage-clock-lwt -I /home/opam/.opam/4.06/lib/mirage-clock-unix -I /home/opam/.opam/4.06/lib/mirage-device -I /home/opam/.opam/4.06/lib/mirage-flow -I /home/opam/.opam/4.06/lib/mirage-logs -I /home/opam/.opam/4.06/lib/mirage-net -I /home/opam/.opam/4.06/lib/mirage-net-lwt -I /home/opam/.opam/4.06/lib/mirage-net-unix -I /home/opam/.opam/4.06/lib/mirage-profile -I /home/opam/.opam/4.06/lib/mirage-protocols -I /home/opam/.opam/4.06/lib/mirage-protocols-lwt -I /home/opam/.opam/4.06/lib/mirage-random -I /home/opam/.opam/4.06/lib/mirage-runtime -I /home/opam/.opam/4.06/lib/mirage-stack -I /home/opam/.opam/4.06/lib/mirage-stack-lwt -I /home/opam/.opam/4.06/lib/mirage-time -I /home/opam/.opam/4.06/lib/mirage-time-lwt -I /home/opam/.opam/4.06/lib/mirage-unix -I /home/opam/.opam/4.06/lib/ocaml-protoc -I /home/opam/.opam/4.06/lib/ocaml/threads -I /home/opam/.opam/4.06/lib/ocplib-endian -I /home/opam/.opam/4.06/lib/parsexp -I /home/opam/.opam/4.06/lib/ppx_deriving -I /home/opam/.opam/4.06/lib/ppx_deriving_protobuf -I /home/opam/.opam/4.06/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.06/lib/ptime -I /home/opam/.opam/4.06/lib/randomconv -I /home/opam/.opam/4.06/lib/re -I /home/opam/.opam/4.06/lib/re/posix -I /home/opam/.opam/4.06/lib/result -I /home/opam/.opam/4.06/lib/rresult -I /home/opam/.opam/4.06/lib/sexplib -I /home/opam/.opam/4.06/lib/sexplib0 -I /home/opam/.opam/4.06/lib/stringext -I /home/opam/.opam/4.06/lib/tcpip -I /home/opam/.opam/4.06/lib/tcpip/ethif -I /home/opam/.opam/4.06/lib/tcpip/icmpv4 -I /home/opam/.opam/4.06/lib/tcpip/ipv4 -I /home/opam/.opam/4.06/lib/tcpip/ipv6 -I /home/opam/.opam/4.06/lib/tcpip/stack-socket -I /home/opam/.opam/4.06/lib/tcpip/tcp_socket_options -I /home/opam/.opam/4.06/lib/tcpip/tcpv4-socket -I /home/opam/.opam/4.06/lib/tcpip/udp -I /home/opam/.opam/4.06/lib/tcpip/udpv4-socket -I /home/opam/.opam/4.06/lib/tcpip/unix -I /home/opam/.opam/4.06/lib/tuntap -I /home/opam/.opam/4.06/lib/uchar -I /home/opam/.opam/4.06/lib/uri -I proto/.lambda_protobuf.objs -I src/.lambda.objs -no-alias-deps -o mirage/.main.eobjs/unikernel.cmo -c -impl mirage/unikernel.ml)
File "mirage/unikernel.ml", line 99, characters 47-63:
Error: This expression has type B.page_aligned_buffer -> bytes
       but an expression was expected of type B.page_aligned_buffer -> string
       Type bytes is not compatible with type string
    ocamlopt proto/.lambda_protobuf.objs/lambda_protobuf.{cmx,o} (exit 2)
(cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -w -30 -g -I proto/.lambda_protobuf.objs -I /home/opam/.opam/4.06/lib/afl-persistent -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/cmdliner -I /home/opam/.opam/4.06/lib/crowbar -I /home/opam/.opam/4.06/lib/cstruct -I /home/opam/.opam/4.06/lib/fmt -I /home/opam/.opam/4.06/lib/higher -I /home/opam/.opam/4.06/lib/logs -I /home/opam/.opam/4.06/lib/lwt -I /home/opam/.opam/4.06/lib/ocaml-protoc -I /home/opam/.opam/4.06/lib/ocplib-endian -I /home/opam/.opam/4.06/lib/parsexp -I /home/opam/.opam/4.06/lib/ppx_deriving -I /home/opam/.opam/4.06/lib/ppx_deriving_protobuf -I /home/opam/.opam/4.06/lib/result -I /home/opam/.opam/4.06/lib/sexplib -I /home/opam/.opam/4.06/lib/sexplib0 -I /home/opam/.opam/4.06/lib/uchar -I src/.lambda.objs -no-alias-deps -open Lambda_protobuf__ -o proto/.lambda_protobuf.objs/lambda_protobuf.cmx -c -impl proto/lambda_protobuf.ml)
File "proto/lambda_protobuf.ml", line 133, characters 30-35:
Error: This expression has type bytes but an expression was expected of type
         string
The command '/bin/sh -c opam exec -- jbuilder build mirage/main.exe' returned a non-zero code: 1
```

**Comment by dinosaure** [comment]
Fixed.

**Comment by aherrmann** [comment]
@dinosaure Thanks! There were still some type errors in `mirage/unikernel.ml`. I've fixed them [here](https://github.com/aherrmann/mirage-lambda/commit/574441d68e0dc4ba9c7904a58a5437389473881f).

**Comment by samoht** [comment]
New docker image pushed to `samoht/mirage-lambda`.

**Pull request merged**
